import os


KOMMO_API_TOKEN = os.getenv("KOMMO_API_TOKEN")
KOMMO_API_SUBDOMAIN = os.getenv("KOMMO_API_SUBDOMAIN")


EVOLUTION_API_URL = os.getenv("EVOLUTION_API_BASE_URL")
EVOLUTION_API_KEY = os.getenv("EVOLUTION_API_AUTHENTICATION_API_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")


DB_HOST = os.getenv("DB_HOST")
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_NAME = os.getenv("DB_NAME")


ID_STATUS_QUALIFICACAO_HUMANA = 96744300